FROM golang:1.24.2 AS builder

WORKDIR /Dashboard_Schedule
COPY go.mod go.sum ./
RUN go mod download

COPY . . 
RUN go build -o server ./cmd/server

FROM golang:latest
WORKDIR /Dashboard_Schedule

COPY --from=builder /Dashboard_Schedule/server .

EXPOSE 8080

CMD [ "./server" ]