// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/group-load/{group.id}": {
            "get": {
                "description": "Возвращает количество пар группы",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Статистика"
                ],
                "summary": "Получение загруженности групп",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GroupLoad"
                        }
                    }
                }
            }
        },
        "/groups": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Получить список групп",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Group"
                            }
                        }
                    }
                }
            }
        },
        "/overall-load": {
            "get": {
                "description": "Возвращает общее количество пар",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Статистика"
                ],
                "summary": "Получение общей загруженности",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OverallLoad"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Group": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "group_title": {
                    "type": "string"
                }
            }
        },
        "models.GroupLoad": {
            "type": "object",
            "properties": {
                "group_title": {
                    "type": "string"
                },
                "pairs_count": {
                    "type": "integer"
                }
            }
        },
        "models.OverallLoad": {
            "type": "object",
            "properties": {
                "total_pairs": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Schedule Dashboard API",
	Description:      "Это API для аналитического дашборда расписания.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
